name: CI-CD

on:
  push:
    branches:
      - '*'

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test -- --coverage

    - name: Build
      run: npm run build -- --base="/2020"

    - name: Deploy to production
      if: github.ref == 'refs/heads/master'
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
