name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test -- --watchAll=false
